FROM ruby:2.7.2

WORKDIR /myapp

COPY ./api/Gemfile /myapp/Gemfile

COPY ./api/Gemfile.lock /myapp/Gemfile.lock

RUN bundle install

COPY ./api/entrypoint.sh /usr/bin/

RUN chmod +x /usr/bin/entrypoint.sh

ENTRYPOINT ["entrypoint.sh"]